version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t rasa-chatbot .
      - run: docker run --rm --volume $(pwd):/app --workdir /app rasa-chatbot rasa data validate